[auth0]
client_id = "Ec5Z4DuNAAlrrFNqldOmIQ8dJ5xYmAy8"
client_secret = "Rm4feHEooAxOZec3S7_2jfFDiSSQ6tYrzxIxfIwRy2L9I0pSFeIR-9TCa8NSKU28"
domain = "dev-5na6o7a8kl28dh6c.us.auth0.com"
redirect_uri = "https://codingsite-3udnejsbf4xtvuv8yxgrbu.streamlit.app"
