[auth0]
client_id = "Ec5Z4DuNAAlrrFNqldOmIQ8dJ5xYmAy8"
client_secret = "YOUR_REAL_CLIENT_SECRET_HERE"
domain = "dev-5na6o7a8kl28dh6c.us.auth0.com"
redirect_uri = "https://codingsite-3udnejsbf4xtvuv8yxgrbu.streamlit.app"

